# Header
menu:
  HOME: /
banner: https://qiniu.miiiku.xyz/src/images/banner.jpg
# banner: css/images/banner.jpg
# logo: https://qiniu.miiiku.xyz/src/images/logo.png

# large cover
large_legnth: 20

# 一言
# docs: https://hitokoto.cn/api
# type: [a, b, c, d, e, f, g]
hitokoto:
  enable: true
  type: a

# valine 评论
# docs: https://valine.js.org
# You can get your appid and appkey from https://leancloud.cn
valine:
  enable: false
  appId: 
  appKey: 
  avatar: mm
  placeholder: 随便说点什么叭～
  notify: true
  visitor: true
  pageSize: 10

disqus:
  enable: false
  website: 
  error: 如果你看不到评论，那么就真的看不到评论 w(゜Д゜)w

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true
  lrcType: 3

# waterfall 瀑布流
# docs: https://github.com/miiiku/waterfall
# Specific configuration information go to `layout/plug-in/waterfall.ejs`
waterfall:
  enable: true

# zoom 图片预览
# docs: https://github.com/miiiku/zoom
# Specific configuration information go to `layout/plug-in/zoom.ejs`
zoom:
  enable: true


# widget behavior
archive_type: 'monthly'
show_count: false

# beian
beian: 

# Miscellaneous
google_analytics: 
gauges_analytics: 
baidu_analytics: 
tencent_analytics: 
favicon: /favicon.ico


# Social Icon
social_icon:
  header_enable: false
  footer_enable: false
  icons:
    - { type: email,      value: }
    - { type: github,     value: }
    - { type: google+,    value: }
    - { type: ins,        value: }
    - { type: twitter,    value: }
    - { type: youtube,    value: }
    - { type: weibo,      value: }
    - { type: cloudmusic, value: }
    - { type: zhihu,      value: }